Dream.create(date: 10/13/2017, keywords: "park", hours_slept: 8, lucid_dream?: true, summary: "walked in park", user_id: 9)
Dream.create(date: 12/02/2017, keywords: "city", hours_slept: 8, lucid_dream?: true, summary: "walked in park", user_id: 9)
Dream.create(date: 12/01/2017, keywords: "hospital", hours_slept: 8, lucid_dream?: true, summary: "walked in hospital", user_id: 9)
Dream.create(date: 10/30/2017, keywords: "chair", hours_slept: 8, lucid_dream?: true, summary: "sat in chair", user_id: 9)
Dream.create(date: 10/27/2017, keywords: "room", hours_slept: 8, lucid_dream?: true, summary: "walked in room", user_id: 9)
Dream.create(date: 10/15/2017, keywords: "freeway", hours_slept: 8, lucid_dream?: true, summary: "drove on freeway", user_id: 9)
Dream.create(date: 10/29/2017, keywords: "car", hours_slept: 8, lucid_dream?: true, summary: "drove in car", user_id: 9)
Dream.create(date: 12/13/2017, keywords: "sleep", hours_slept: 8, lucid_dream?: true, summary: "slept", user_id: 9)
Dream.create(date: 12/03/2017, keywords: "dogs", hours_slept: 8, lucid_dream?: true, summary: "walked 10 dogs", user_id: 9)
Dream.create(date: 12/07/2017, keywords: "happy", hours_slept: 8, lucid_dream?: true, summary: "felt happy", user_id: 9)
Dream.create(date: 10/23/2017, keywords: "books", hours_slept: 8, lucid_dream?: true, summary: "organized books", user_id: 9)
Dream.create(date: 12/06/2017, keywords: "writing", hours_slept: 8, lucid_dream?: true, summary: "wrote a novel", user_id: 9)
Dream.create(date: 10/28/2017, keywords: "sick", hours_slept: 8, lucid_dream?: true, summary: "stayed home sick", user_id: 9)
Dream.create(date: 10/22/2017, keywords: "party", hours_slept: 8, lucid_dream?: true, summary: "went to party", user_id: 9)
Dream.create(date: 10/11/2017, keywords: "quiet", hours_slept: 8, lucid_dream?: true, summary: "sat in quiet room", user_id: 9)
Dream.create(date: 10/10/2017, keywords: "jungle", hours_slept: 8, lucid_dream?: true, summary: "walked in jungle", user_id: 9)
Dream.create(date: 10/17/2017, keywords: "movies", hours_slept: 8, lucid_dream?: true, summary: "went to movies", user_id: 9)
Dream.create(date: 10/14/2017, keywords: "clown", hours_slept: 8, lucid_dream?: true, summary: "clowns", user_id: 9)
Dream.create(date: 10/19/2017, keywords: "candy", hours_slept: 8, lucid_dream?: true, summary: "ate candy", user_id: 9)
Dream.create(date: 12/09/2017, keywords: "shopping", hours_slept: 8, lucid_dream?: true, summary: "went shopping", user_id: 9)
Dream.create(date: 12/03/2017, keywords: "magazine", hours_slept: 8, lucid_dream?: true, summary: "started magazine", user_id: 9)
Dream.create(date: 10/23/2017, keywords: "iphone", hours_slept: 8, lucid_dream?: true, summary: "invented iphone", user_id: 9)
Dream.create(date: 10/27/2017, keywords: "concert", hours_slept: 8, lucid_dream?: true, summary: "went to concert", user_id: 9)
Dream.create(date: 10/17/2017, keywords: "guitar", hours_slept: 8, lucid_dream?: true, summary: "played guitar", user_id: 9)
Dream.create(date: 10/13/2017, keywords: "vitamins", hours_slept: 8, lucid_dream?: true, summary: "took my vitamins", user_id: 9)
Dream.create(date: 10/19/2017, keywords: "fire", hours_slept: 8, lucid_dream?: true, summary: "walked in fire", user_id: 9)
Dream.create(date: 12/10/2017, keywords: "tv", hours_slept: 8, lucid_dream?: true, summary: "watched tv", user_id: 9)
